graph RL

    %% 
    %% Name: loop.mmd
    %% Description: 
    %% 
    %% Created Date: February 2024
    %% Author:
    %% 		Lukáš Laštůvka
    %% 		https://github.com/LastuvkaLukas
    %% 
    %% License: Apache License 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
    %% Copyright (c) 2024 Lukáš Laštůvka
    %% 

    %% Styles
    classDef mainNode fill:#000,color:#fff,stroke:#000000,stroke-width:2px;
    classDef greenNode fill:#77DD77,stroke:#000000,stroke-width:2px;
    classDef yellowNode fill:#F7DC6F,stroke:#000000,stroke-width:2px;
    classDef redNode fill:#FF5733,stroke:#000000,stroke-width:2px;

    %% Nodes
    Main(<b>Loop)
    A(<b>Emergency)
    B(<b>Sensor)
    C(<b>Mode)
    D(<b>Endstop)
    E(<b>Servo)
    F(<b>LoRa)

    %% Set styles
    class Main mainNode
    class A,B,C,D,E,F greenNode;

    %% Diagram
    Main --> Sub1
    subgraph Sub1[<b>States]
    direction LR
        A --> B
        B --> C
        C --> D
        D --> E
        E --> F
    end
    Sub1 --> Main